import { DefineComponent } from "vue";
import { PoTopBar } from "./PoTopBar/PoTopBar.vue";
import { PoAppIcon } from "./PoAppIcon/PoAppIcon.vue";
import { PoSearchBar } from "./PoSearchBar/PoSearchBar.vue";
import { PoAppTray } from "./PoAppTray/PoAppTray.vue";
import { PoNotificationHub } from "./PoNotificationHub/PoNotificationHub.vue";
import { PoProfileSwitcher } from "./PoProfileSwitcher/PoProfileSwitcher.vue";
import { PoSidebarDrawer } from "./PoSidebarDrawer/PoSidebarDrawer.vue";
import { PoActionBar } from "./PoActionBar/PoActionBar.vue";
import { PoCard } from "./PoCard/PoCard.vue";
import { PoCardSearch } from "./PoCardSearch/PoCardSearch.vue";
import { PoPageTitle } from "./PoPageTitle/PoPageTitle.vue";
import { PoPagination } from "./PoPagination/PoPagination.vue";
import { PoTable } from "./PoTable/PoTable.vue";
import { PoDescriptionList } from "./PoDescriptionList/PoDescriptionList.vue";
import { PoInputField } from "./PoInputField/PoInputField.vue";
import { PoInputFile } from "./PoInputFile/PoInputFile.vue";
import { PoSelectField } from "./PoSelectField/PoSelectField.vue";
import { PoButton } from "./PoButton/PoButton.vue";
import { PoModal } from "./PoModal/PoModal.vue";
import { PoToggle } from "./PoToggle/PoToggle.vue";
import { PoSectionMenu } from "./PoSectionMenu/PoSectionMenu.vue";
import { PoCheckbox } from "./PoCheckbox/PoCheckbox.vue";
import { PoTextarea } from "./PoTextarea/PoTextarea.vue";
import { PoFooter } from "./PoFooter/PoFooter.vue";
import { PoFormStatusMessage } from "./PoFormStatusMessage/PoFormStatusMessage.vue";
import { PoRadioInput } from "./PoRadioInput/PoRadioInput.vue";
import { PoStatsBlock } from "./PoStatsBlock/PoStatsBlock.vue";
import { PoChatLogItem } from "./PoChatLogItem/PoChatLogItem.vue";
import { PoNotification } from "./PoNotification/PoNotification.vue";
import { PoSlideover } from "./PoSlideover/PoSlideover.vue";
import { PoCommandPalette } from "./PoCommandPalette/PoCommandPalette.vue";
import { PoAlert } from "./PoAlert/PoAlert.vue";
import { PoLogs } from "./PoLogs/PoLogs.vue";
import { PoDownloadFileList } from "./PoDownloadFileList/PoDownloadFileList.vue";
import { PoContentArea } from "./PoContentArea/PoContentArea.vue";
import { PoLoading } from "./PoLoading/PoLoading.vue";
import { PoConsent } from "./PoConsent/PoConsent.vue";
import { PoCardTabs } from "./PoCardTabs/PoCardTabs.vue";
import { PoTabs } from "./PoTabs/PoTabs.vue";
import { PoEmpty } from "./PoEmpty/PoEmpty.vue";
import { PoDRStatus } from "./PoDRStatus/PoDRStatus.vue";
import { PoTableAction } from "./PoTableAction/PoTableAction.vue";
import { Rufiyaa } from "./Rufiyaa/Rufiyaa.vue";
import { PoHeading } from "./PoHeading/PoHeading.vue";
import { PoMultiSelect } from "./PoMultiSelect/PoMultiSelect.vue";
import { PoTimeline } from "./PoTimeline/PoTimeline.vue";
import { PoTableCheckbox } from "./PoTableCheckbox/PoTableCheckbox.vue";
import { PoToast } from "./PoToast/PoToast.vue";
import { PoSelectApi } from "./PoSelectApi/PoSelectApi.vue";
import { PoMessage } from "./PoMessage/PoMessage.vue";
import { PoPageStats } from "./PoPageStats/PoPageStats.vue";
import { PoTooltip } from "./PoTooltip/PoTooltip.vue";
import { PoUpload } from "./PoUpload/PoUpload.vue";

declare module "./index" {
	const component: DefineComponent<{}, {}, any> & {
		PoTopBar: typeof PoTopBar;
		PoAppIcon: typeof PoAppIcon;
		PoSearchBar: typeof PoSearchBar;
		PoAppTray: typeof PoAppTray;
		PoNotificationHub: typeof PoNotificationHub;
		PoProfileSwitcher: typeof PoProfileSwitcher;
		PoSidebarDrawer: typeof PoSidebarDrawer;
		PoActionBar: typeof PoActionBar;
		PoCard: typeof PoCard;
		PoCardSearch: typeof PoCardSearch;
		PoPageTitle: typeof PoPageTitle;
		PoPagination: typeof PoPagination;
		PoTable: typeof PoTable;
		PoDescriptionList: typeof PoDescriptionList;
		PoInputField: typeof PoInputField;
		PoInputFile: typeof PoInputFile;
		PoSelectField: typeof PoSelectField;
		PoButton: typeof PoButton;
		PoModal: typeof PoModal;
		PoToggle: typeof PoToggle;
		PoSectionMenu: typeof PoSectionMenu;
		PoCheckbox: typeof PoCheckbox;
		PoTextarea: typeof PoTextarea;
		PoFooter: typeof PoFooter;
		PoFormStatusMessage: typeof PoFormStatusMessage;
		PoRadioInput: typeof PoRadioInput;
		PoStatsBlock: typeof PoStatsBlock;
		PoChatLogItem: typeof PoChatLogItem;
		PoNotification: typeof PoNotification;
		PoSlideover: typeof PoSlideover;
		PoCommandPalette: typeof PoCommandPalette;
		PoAlert: typeof PoAlert;
		PoLogs: typeof PoLogs;
		PoDownloadFileList: typeof PoDownloadFileList;
		PoContentArea: typeof PoContentArea;
		PoLoading: typeof PoLoading;
		PoConsent: typeof PoConsent;
		PoCardTabs: typeof PoCardTabs;
		PoTabs: typeof PoTabs;
		PoEmpty: typeof PoEmpty;
		PoDRStatus: typeof PoDRStatus;
		PoTableAction: typeof PoTableAction;
		Rufiyaa: typeof Rufiyaa;
		PoHeading: typeof PoHeading;
		PoMultiSelect: typeof PoMultiSelect;
		PoTimeline: typeof PoTimeline;
		PoTableCheckbox: typeof PoTableCheckbox;
		PoToast: typeof PoToast;
		PoSelectApi: typeof PoSelectApi;
		PoMessage: typeof PoMessage;
		PoPageStats: typeof PoPageStats;
		PoTooltip: typeof PoTooltip;
		PoUpload: typeof PoUpload;
	};

	export default component;
}
